import { ClerkProvider } from "@clerk/nextjs";

import type { Metadata } from "next";
import { Poppins, Urbanist } from "next/font/google";
import "./globals.css";

import React from "react";
import { ThemeProvider } from "@/context/ThemeProvider";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-urbanist",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} ${poppins.className}`}>
        <ClerkProvider
          appearance={{
            elements: {
              formButtonPrimary: "bg-primary-500",
            },
          }}
        >
          <ThemeProvider>{children}</ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
